-- MySQL Script generated by MySQL Workbench
-- Tue May 27 19:07:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sistem` ;

-- -----------------------------------------------------
-- Schema Sistem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistem` DEFAULT CHARACTER SET utf8 ;
USE `Sistem` ;

-- -----------------------------------------------------
-- Table `Sistem`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistem`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `Sistem`.`USUARIO` (
  `ID` INT UNSIGNED NOT NULL auto_increment,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `TIPO_USUARIO` ENUM("USUARIO", "ADM") NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;
select * from USUARIO;

INSERT INTO USUARIO (NOME, EMAIL,SENHA,TIPO_USUARIO)
VALUES 
	('DEIVIN', 'ana@email.com', 28,'ADM'),
    ('Maria puple', 'maria@email.com', 25,'ADM'),
    ('mica grau', 'pedro@email.com', 35, 'USUARIO'),
    ('dan dan', 'ana@email.com', 28,'ADM');



-- -----------------------------------------------------
-- Table `Sistem`.`NOTICIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistem`.`NOTICIAS` ;

CREATE TABLE IF NOT EXISTS `Sistem`.`NOTICIAS` (
  `idNOTICIAS` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `SUB_TITULO` VARCHAR(45) NOT NULL,
  `DESCRICAO1` VARCHAR(225) NOT NULL,
  `FOTO_CAPA` VARCHAR(45) NOT NULL,
  `CONTEUDO` VARCHAR(45) NULL,
  `AUTOR_ID` INT UNSIGNED NULL,
  PRIMARY KEY (`idNOTICIAS`),
  INDEX `fk_NOTICIAS_USUARIO1_idx` (`AUTOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NOTICIAS_USUARIO1`
    FOREIGN KEY (`AUTOR_ID`)
    REFERENCES `Sistem`.`USUARIO` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
select * FROM NOTICIAS;

INSERT INTO  `Sistem`.`NOTICIAS` (`TITULO`, `SUB_TITULO`, `DESCRICAO1`, `FOTO_CAPA`, `CONTEUDO`, `AUTOR_ID`) VALUES
('Título 1', 'Subtítulo 1', 'Descrição da notícia1 ', 'capa1.jpg', 'Conteúdo da notícia 1 detalhado.', 3),
('Título 2', 'Subtítulo 2', 'Descrição da notícia2 ', 'capa2.jpg', 'Conteúdo da notícia 2 com mais texto.',1);


-- -----------------------------------------------------
-- Table `Sistem`.`COMENTARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistem`.`COMENTARIO` ;

CREATE TABLE IF NOT EXISTS `Sistem`.`COMENTARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEXTO` VARCHAR(80) NULL,
  `DATA_POST` TIMESTAMP NULL,
  `USUARIO_ID` INT UNSIGNED NOT NULL,
  `NOTICIAS_idNOTICIAS` INT NOT NULL,
  PRIMARY KEY (`ID`, `USUARIO_ID`, `NOTICIAS_idNOTICIAS`),
  INDEX `fk_COMENTARIO_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  INDEX `fk_COMENTARIO_NOTICIAS1_idx` (`NOTICIAS_idNOTICIAS` ASC) VISIBLE,
  CONSTRAINT `fk_COMENTARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `Sistem`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_NOTICIAS1`
    FOREIGN KEY (`NOTICIAS_idNOTICIAS`)
    REFERENCES `Sistem`.`NOTICIAS` (`idNOTICIAS`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
SELECT * FROM COMENTARIO;

INSERT INTO `COMENTARIO` (`TEXTO`, `USUARIO_ID`, `NOTICIAS_IDNOTICIAS`) VALUES
('Ótima notícia!', 1,1 ),
('Parabéns pela matéria.', 2, 1),
('Gostei do conteúdo.', 3, 2);


-- -----------------------------------------------------
-- Table `Sistem`.`midia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistem`.`midia` ;

CREATE TABLE IF NOT EXISTS `Sistem`.`midia` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `midia` VARCHAR(45) NOT NULL,
  `TIPO_MIDIA` VARCHAR(45) NOT NULL,
  `NOTICIAS_idNOTICIAS` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_midia_NOTICIAS1_idx` (`NOTICIAS_idNOTICIAS` ASC) VISIBLE,
  CONSTRAINT `fk_midia_NOTICIAS1`
    FOREIGN KEY (`NOTICIAS_idNOTICIAS`)
    REFERENCES `Sistem`.`NOTICIAS` (`idNOTICIAS`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SELECT * FROM midia;

INSERT INTO `MIDIA` (`MIDIA`, `TIPO_MIDIA`, `NOTICIAS_IDNOTICIAS`) VALUES
('foto1.jpg', 'imagem', 1),
('video1.mp4', 'vídeo', 2);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
